/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-09-18 at 15:48:45 UTC 
 * Modify at your own risk.
 */

package com.sep.androidbuddy.service.userrelateddataservice;

/**
 * Service definition for Userrelateddataservice (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link UserrelateddataserviceRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Userrelateddataservice extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the userrelateddataservice library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "userrelateddataservice/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Userrelateddataservice(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Userrelateddataservice(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getLastLog".
   *
   * This request holds the parameters needed by the userrelateddataservice server.  After setting any
   * optional parameters, call the {@link GetLastLog#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetLastLog getLastLog(java.lang.String id) throws java.io.IOException {
    GetLastLog result = new GetLastLog(id);
    initialize(result);
    return result;
  }

  public class GetLastLog extends UserrelateddataserviceRequest<com.sep.androidbuddy.service.userrelateddataservice.model.LastLogDetailCollection> {

    private static final String REST_PATH = "lastlogdetailcollection/{Id}";

    protected GetLastLog(java.lang.String id) {
      super(Userrelateddataservice.this, "GET", REST_PATH, null, com.sep.androidbuddy.service.userrelateddataservice.model.LastLogDetailCollection.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetLastLog setAlt(java.lang.String alt) {
      return (GetLastLog) super.setAlt(alt);
    }

    @Override
    public GetLastLog setFields(java.lang.String fields) {
      return (GetLastLog) super.setFields(fields);
    }

    @Override
    public GetLastLog setKey(java.lang.String key) {
      return (GetLastLog) super.setKey(key);
    }

    @Override
    public GetLastLog setOauthToken(java.lang.String oauthToken) {
      return (GetLastLog) super.setOauthToken(oauthToken);
    }

    @Override
    public GetLastLog setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetLastLog) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetLastLog setQuotaUser(java.lang.String quotaUser) {
      return (GetLastLog) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetLastLog setUserIp(java.lang.String userIp) {
      return (GetLastLog) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key("Id")
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetLastLog setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetLastLog set(String parameterName, Object value) {
      return (GetLastLog) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listCallLogBySecificDate".
   *
   * This request holds the parameters needed by the userrelateddataservice server.  After setting any
   * optional parameters, call the {@link ListCallLogBySecificDate#execute()} method to invoke the
   * remote operation.
   *
   * @param callType
   * @param startTime
   * @param userId
   * @return the request
   */
  public ListCallLogBySecificDate listCallLogBySecificDate(java.lang.String callType, java.lang.String startTime, java.lang.String userId) throws java.io.IOException {
    ListCallLogBySecificDate result = new ListCallLogBySecificDate(callType, startTime, userId);
    initialize(result);
    return result;
  }

  public class ListCallLogBySecificDate extends UserrelateddataserviceRequest<com.sep.androidbuddy.service.userrelateddataservice.model.CallLogCollection> {

    private static final String REST_PATH = "calllog/type";

    /**
     * Create a request for the method "listCallLogBySecificDate".
     *
     * This request holds the parameters needed by the the userrelateddataservice server.  After
     * setting any optional parameters, call the {@link ListCallLogBySecificDate#execute()} method to
     * invoke the remote operation. <p> {@link ListCallLogBySecificDate#initialize(com.google.api.clie
     * nt.googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param callType
     * @param startTime
     * @param userId
     * @since 1.13
     */
    protected ListCallLogBySecificDate(java.lang.String callType, java.lang.String startTime, java.lang.String userId) {
      super(Userrelateddataservice.this, "GET", REST_PATH, null, com.sep.androidbuddy.service.userrelateddataservice.model.CallLogCollection.class);
      this.callType = com.google.api.client.util.Preconditions.checkNotNull(callType, "Required parameter callType must be specified.");
      this.startTime = com.google.api.client.util.Preconditions.checkNotNull(startTime, "Required parameter startTime must be specified.");
      this.userId = com.google.api.client.util.Preconditions.checkNotNull(userId, "Required parameter userId must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListCallLogBySecificDate setAlt(java.lang.String alt) {
      return (ListCallLogBySecificDate) super.setAlt(alt);
    }

    @Override
    public ListCallLogBySecificDate setFields(java.lang.String fields) {
      return (ListCallLogBySecificDate) super.setFields(fields);
    }

    @Override
    public ListCallLogBySecificDate setKey(java.lang.String key) {
      return (ListCallLogBySecificDate) super.setKey(key);
    }

    @Override
    public ListCallLogBySecificDate setOauthToken(java.lang.String oauthToken) {
      return (ListCallLogBySecificDate) super.setOauthToken(oauthToken);
    }

    @Override
    public ListCallLogBySecificDate setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListCallLogBySecificDate) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListCallLogBySecificDate setQuotaUser(java.lang.String quotaUser) {
      return (ListCallLogBySecificDate) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListCallLogBySecificDate setUserIp(java.lang.String userIp) {
      return (ListCallLogBySecificDate) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String callType;

    /**

     */
    public java.lang.String getCallType() {
      return callType;
    }

    public ListCallLogBySecificDate setCallType(java.lang.String callType) {
      this.callType = callType;
      return this;
    }

    @com.google.api.client.util.Key("start_time")
    private java.lang.String startTime;

    /**

     */
    public java.lang.String getStartTime() {
      return startTime;
    }

    public ListCallLogBySecificDate setStartTime(java.lang.String startTime) {
      this.startTime = startTime;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String userId;

    /**

     */
    public java.lang.String getUserId() {
      return userId;
    }

    public ListCallLogBySecificDate setUserId(java.lang.String userId) {
      this.userId = userId;
      return this;
    }

    @Override
    public ListCallLogBySecificDate set(String parameterName, Object value) {
      return (ListCallLogBySecificDate) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listCallLogByTimePeriod".
   *
   * This request holds the parameters needed by the userrelateddataservice server.  After setting any
   * optional parameters, call the {@link ListCallLogByTimePeriod#execute()} method to invoke the
   * remote operation.
   *
   * @param userId
   * @param startTime
   * @param endTime
   * @param callType
   * @return the request
   */
  public ListCallLogByTimePeriod listCallLogByTimePeriod(java.lang.String userId, java.lang.String startTime, java.lang.String endTime, java.lang.String callType) throws java.io.IOException {
    ListCallLogByTimePeriod result = new ListCallLogByTimePeriod(userId, startTime, endTime, callType);
    initialize(result);
    return result;
  }

  public class ListCallLogByTimePeriod extends UserrelateddataserviceRequest<com.sep.androidbuddy.service.userrelateddataservice.model.CallLogCollection> {

    private static final String REST_PATH = "calllog/{userId}/{start_time}/{end_time}/{callType}";

    /**
     * Create a request for the method "listCallLogByTimePeriod".
     *
     * This request holds the parameters needed by the the userrelateddataservice server.  After
     * setting any optional parameters, call the {@link ListCallLogByTimePeriod#execute()} method to
     * invoke the remote operation. <p> {@link ListCallLogByTimePeriod#initialize(com.google.api.clien
     * t.googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param userId
     * @param startTime
     * @param endTime
     * @param callType
     * @since 1.13
     */
    protected ListCallLogByTimePeriod(java.lang.String userId, java.lang.String startTime, java.lang.String endTime, java.lang.String callType) {
      super(Userrelateddataservice.this, "GET", REST_PATH, null, com.sep.androidbuddy.service.userrelateddataservice.model.CallLogCollection.class);
      this.userId = com.google.api.client.util.Preconditions.checkNotNull(userId, "Required parameter userId must be specified.");
      this.startTime = com.google.api.client.util.Preconditions.checkNotNull(startTime, "Required parameter startTime must be specified.");
      this.endTime = com.google.api.client.util.Preconditions.checkNotNull(endTime, "Required parameter endTime must be specified.");
      this.callType = com.google.api.client.util.Preconditions.checkNotNull(callType, "Required parameter callType must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListCallLogByTimePeriod setAlt(java.lang.String alt) {
      return (ListCallLogByTimePeriod) super.setAlt(alt);
    }

    @Override
    public ListCallLogByTimePeriod setFields(java.lang.String fields) {
      return (ListCallLogByTimePeriod) super.setFields(fields);
    }

    @Override
    public ListCallLogByTimePeriod setKey(java.lang.String key) {
      return (ListCallLogByTimePeriod) super.setKey(key);
    }

    @Override
    public ListCallLogByTimePeriod setOauthToken(java.lang.String oauthToken) {
      return (ListCallLogByTimePeriod) super.setOauthToken(oauthToken);
    }

    @Override
    public ListCallLogByTimePeriod setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListCallLogByTimePeriod) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListCallLogByTimePeriod setQuotaUser(java.lang.String quotaUser) {
      return (ListCallLogByTimePeriod) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListCallLogByTimePeriod setUserIp(java.lang.String userIp) {
      return (ListCallLogByTimePeriod) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String userId;

    /**

     */
    public java.lang.String getUserId() {
      return userId;
    }

    public ListCallLogByTimePeriod setUserId(java.lang.String userId) {
      this.userId = userId;
      return this;
    }

    @com.google.api.client.util.Key("start_time")
    private java.lang.String startTime;

    /**

     */
    public java.lang.String getStartTime() {
      return startTime;
    }

    public ListCallLogByTimePeriod setStartTime(java.lang.String startTime) {
      this.startTime = startTime;
      return this;
    }

    @com.google.api.client.util.Key("end_time")
    private java.lang.String endTime;

    /**

     */
    public java.lang.String getEndTime() {
      return endTime;
    }

    public ListCallLogByTimePeriod setEndTime(java.lang.String endTime) {
      this.endTime = endTime;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String callType;

    /**

     */
    public java.lang.String getCallType() {
      return callType;
    }

    public ListCallLogByTimePeriod setCallType(java.lang.String callType) {
      this.callType = callType;
      return this;
    }

    @Override
    public ListCallLogByTimePeriod set(String parameterName, Object value) {
      return (ListCallLogByTimePeriod) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listCallLogByUser".
   *
   * This request holds the parameters needed by the userrelateddataservice server.  After setting any
   * optional parameters, call the {@link ListCallLogByUser#execute()} method to invoke the remote
   * operation.
   *
   * @param userId
   * @return the request
   */
  public ListCallLogByUser listCallLogByUser(java.lang.String userId) throws java.io.IOException {
    ListCallLogByUser result = new ListCallLogByUser(userId);
    initialize(result);
    return result;
  }

  public class ListCallLogByUser extends UserrelateddataserviceRequest<com.sep.androidbuddy.service.userrelateddataservice.model.CallLogCollection> {

    private static final String REST_PATH = "calllog/{userId}";

    /**
     * Create a request for the method "listCallLogByUser".
     *
     * This request holds the parameters needed by the the userrelateddataservice server.  After
     * setting any optional parameters, call the {@link ListCallLogByUser#execute()} method to invoke
     * the remote operation. <p> {@link ListCallLogByUser#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param userId
     * @since 1.13
     */
    protected ListCallLogByUser(java.lang.String userId) {
      super(Userrelateddataservice.this, "GET", REST_PATH, null, com.sep.androidbuddy.service.userrelateddataservice.model.CallLogCollection.class);
      this.userId = com.google.api.client.util.Preconditions.checkNotNull(userId, "Required parameter userId must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListCallLogByUser setAlt(java.lang.String alt) {
      return (ListCallLogByUser) super.setAlt(alt);
    }

    @Override
    public ListCallLogByUser setFields(java.lang.String fields) {
      return (ListCallLogByUser) super.setFields(fields);
    }

    @Override
    public ListCallLogByUser setKey(java.lang.String key) {
      return (ListCallLogByUser) super.setKey(key);
    }

    @Override
    public ListCallLogByUser setOauthToken(java.lang.String oauthToken) {
      return (ListCallLogByUser) super.setOauthToken(oauthToken);
    }

    @Override
    public ListCallLogByUser setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListCallLogByUser) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListCallLogByUser setQuotaUser(java.lang.String quotaUser) {
      return (ListCallLogByUser) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListCallLogByUser setUserIp(java.lang.String userIp) {
      return (ListCallLogByUser) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String userId;

    /**

     */
    public java.lang.String getUserId() {
      return userId;
    }

    public ListCallLogByUser setUserId(java.lang.String userId) {
      this.userId = userId;
      return this;
    }

    @Override
    public ListCallLogByUser set(String parameterName, Object value) {
      return (ListCallLogByUser) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listContactByUser".
   *
   * This request holds the parameters needed by the userrelateddataservice server.  After setting any
   * optional parameters, call the {@link ListContactByUser#execute()} method to invoke the remote
   * operation.
   *
   * @param userId
   * @return the request
   */
  public ListContactByUser listContactByUser(java.lang.String userId) throws java.io.IOException {
    ListContactByUser result = new ListContactByUser(userId);
    initialize(result);
    return result;
  }

  public class ListContactByUser extends UserrelateddataserviceRequest<com.sep.androidbuddy.service.userrelateddataservice.model.ContactCollection> {

    private static final String REST_PATH = "contact/{userId}";

    /**
     * Create a request for the method "listContactByUser".
     *
     * This request holds the parameters needed by the the userrelateddataservice server.  After
     * setting any optional parameters, call the {@link ListContactByUser#execute()} method to invoke
     * the remote operation. <p> {@link ListContactByUser#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param userId
     * @since 1.13
     */
    protected ListContactByUser(java.lang.String userId) {
      super(Userrelateddataservice.this, "GET", REST_PATH, null, com.sep.androidbuddy.service.userrelateddataservice.model.ContactCollection.class);
      this.userId = com.google.api.client.util.Preconditions.checkNotNull(userId, "Required parameter userId must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListContactByUser setAlt(java.lang.String alt) {
      return (ListContactByUser) super.setAlt(alt);
    }

    @Override
    public ListContactByUser setFields(java.lang.String fields) {
      return (ListContactByUser) super.setFields(fields);
    }

    @Override
    public ListContactByUser setKey(java.lang.String key) {
      return (ListContactByUser) super.setKey(key);
    }

    @Override
    public ListContactByUser setOauthToken(java.lang.String oauthToken) {
      return (ListContactByUser) super.setOauthToken(oauthToken);
    }

    @Override
    public ListContactByUser setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListContactByUser) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListContactByUser setQuotaUser(java.lang.String quotaUser) {
      return (ListContactByUser) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListContactByUser setUserIp(java.lang.String userIp) {
      return (ListContactByUser) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String userId;

    /**

     */
    public java.lang.String getUserId() {
      return userId;
    }

    public ListContactByUser setUserId(java.lang.String userId) {
      this.userId = userId;
      return this;
    }

    @Override
    public ListContactByUser set(String parameterName, Object value) {
      return (ListContactByUser) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listContactsBySpecificTime".
   *
   * This request holds the parameters needed by the userrelateddataservice server.  After setting any
   * optional parameters, call the {@link ListContactsBySpecificTime#execute()} method to invoke the
   * remote operation.
   *
   * @param userId
   * @param startTime
   * @return the request
   */
  public ListContactsBySpecificTime listContactsBySpecificTime(java.lang.String userId, java.lang.String startTime) throws java.io.IOException {
    ListContactsBySpecificTime result = new ListContactsBySpecificTime(userId, startTime);
    initialize(result);
    return result;
  }

  public class ListContactsBySpecificTime extends UserrelateddataserviceRequest<com.sep.androidbuddy.service.userrelateddataservice.model.ContactCollection> {

    private static final String REST_PATH = "contact/{userId}/{startTime}";

    /**
     * Create a request for the method "listContactsBySpecificTime".
     *
     * This request holds the parameters needed by the the userrelateddataservice server.  After
     * setting any optional parameters, call the {@link ListContactsBySpecificTime#execute()} method
     * to invoke the remote operation. <p> {@link ListContactsBySpecificTime#initialize(com.google.api
     * .client.googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this
     * instance immediately after invoking the constructor. </p>
     *
     * @param userId
     * @param startTime
     * @since 1.13
     */
    protected ListContactsBySpecificTime(java.lang.String userId, java.lang.String startTime) {
      super(Userrelateddataservice.this, "GET", REST_PATH, null, com.sep.androidbuddy.service.userrelateddataservice.model.ContactCollection.class);
      this.userId = com.google.api.client.util.Preconditions.checkNotNull(userId, "Required parameter userId must be specified.");
      this.startTime = com.google.api.client.util.Preconditions.checkNotNull(startTime, "Required parameter startTime must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListContactsBySpecificTime setAlt(java.lang.String alt) {
      return (ListContactsBySpecificTime) super.setAlt(alt);
    }

    @Override
    public ListContactsBySpecificTime setFields(java.lang.String fields) {
      return (ListContactsBySpecificTime) super.setFields(fields);
    }

    @Override
    public ListContactsBySpecificTime setKey(java.lang.String key) {
      return (ListContactsBySpecificTime) super.setKey(key);
    }

    @Override
    public ListContactsBySpecificTime setOauthToken(java.lang.String oauthToken) {
      return (ListContactsBySpecificTime) super.setOauthToken(oauthToken);
    }

    @Override
    public ListContactsBySpecificTime setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListContactsBySpecificTime) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListContactsBySpecificTime setQuotaUser(java.lang.String quotaUser) {
      return (ListContactsBySpecificTime) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListContactsBySpecificTime setUserIp(java.lang.String userIp) {
      return (ListContactsBySpecificTime) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String userId;

    /**

     */
    public java.lang.String getUserId() {
      return userId;
    }

    public ListContactsBySpecificTime setUserId(java.lang.String userId) {
      this.userId = userId;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String startTime;

    /**

     */
    public java.lang.String getStartTime() {
      return startTime;
    }

    public ListContactsBySpecificTime setStartTime(java.lang.String startTime) {
      this.startTime = startTime;
      return this;
    }

    @Override
    public ListContactsBySpecificTime set(String parameterName, Object value) {
      return (ListContactsBySpecificTime) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listContactsByTimeperiod".
   *
   * This request holds the parameters needed by the userrelateddataservice server.  After setting any
   * optional parameters, call the {@link ListContactsByTimeperiod#execute()} method to invoke the
   * remote operation.
   *
   * @param userId
   * @param startTime
   * @param endtime
   * @return the request
   */
  public ListContactsByTimeperiod listContactsByTimeperiod(java.lang.String userId, java.lang.String startTime, java.lang.String endtime) throws java.io.IOException {
    ListContactsByTimeperiod result = new ListContactsByTimeperiod(userId, startTime, endtime);
    initialize(result);
    return result;
  }

  public class ListContactsByTimeperiod extends UserrelateddataserviceRequest<com.sep.androidbuddy.service.userrelateddataservice.model.ContactCollection> {

    private static final String REST_PATH = "contact/{userId}/{startTime}/{endtime}";

    /**
     * Create a request for the method "listContactsByTimeperiod".
     *
     * This request holds the parameters needed by the the userrelateddataservice server.  After
     * setting any optional parameters, call the {@link ListContactsByTimeperiod#execute()} method to
     * invoke the remote operation. <p> {@link ListContactsByTimeperiod#initialize(com.google.api.clie
     * nt.googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param userId
     * @param startTime
     * @param endtime
     * @since 1.13
     */
    protected ListContactsByTimeperiod(java.lang.String userId, java.lang.String startTime, java.lang.String endtime) {
      super(Userrelateddataservice.this, "GET", REST_PATH, null, com.sep.androidbuddy.service.userrelateddataservice.model.ContactCollection.class);
      this.userId = com.google.api.client.util.Preconditions.checkNotNull(userId, "Required parameter userId must be specified.");
      this.startTime = com.google.api.client.util.Preconditions.checkNotNull(startTime, "Required parameter startTime must be specified.");
      this.endtime = com.google.api.client.util.Preconditions.checkNotNull(endtime, "Required parameter endtime must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListContactsByTimeperiod setAlt(java.lang.String alt) {
      return (ListContactsByTimeperiod) super.setAlt(alt);
    }

    @Override
    public ListContactsByTimeperiod setFields(java.lang.String fields) {
      return (ListContactsByTimeperiod) super.setFields(fields);
    }

    @Override
    public ListContactsByTimeperiod setKey(java.lang.String key) {
      return (ListContactsByTimeperiod) super.setKey(key);
    }

    @Override
    public ListContactsByTimeperiod setOauthToken(java.lang.String oauthToken) {
      return (ListContactsByTimeperiod) super.setOauthToken(oauthToken);
    }

    @Override
    public ListContactsByTimeperiod setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListContactsByTimeperiod) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListContactsByTimeperiod setQuotaUser(java.lang.String quotaUser) {
      return (ListContactsByTimeperiod) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListContactsByTimeperiod setUserIp(java.lang.String userIp) {
      return (ListContactsByTimeperiod) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String userId;

    /**

     */
    public java.lang.String getUserId() {
      return userId;
    }

    public ListContactsByTimeperiod setUserId(java.lang.String userId) {
      this.userId = userId;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String startTime;

    /**

     */
    public java.lang.String getStartTime() {
      return startTime;
    }

    public ListContactsByTimeperiod setStartTime(java.lang.String startTime) {
      this.startTime = startTime;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String endtime;

    /**

     */
    public java.lang.String getEndtime() {
      return endtime;
    }

    public ListContactsByTimeperiod setEndtime(java.lang.String endtime) {
      this.endtime = endtime;
      return this;
    }

    @Override
    public ListContactsByTimeperiod set(String parameterName, Object value) {
      return (ListContactsByTimeperiod) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listInboxMessegeLog".
   *
   * This request holds the parameters needed by the userrelateddataservice server.  After setting any
   * optional parameters, call the {@link ListInboxMessegeLog#execute()} method to invoke the remote
   * operation.
   *
   * @param type
   * @param userId
   * @return the request
   */
  public ListInboxMessegeLog listInboxMessegeLog(java.lang.String type, java.lang.String userId) throws java.io.IOException {
    ListInboxMessegeLog result = new ListInboxMessegeLog(type, userId);
    initialize(result);
    return result;
  }

  public class ListInboxMessegeLog extends UserrelateddataserviceRequest<com.sep.androidbuddy.service.userrelateddataservice.model.MessegeLogCollection> {

    private static final String REST_PATH = "messegelog/bytype";

    /**
     * Create a request for the method "listInboxMessegeLog".
     *
     * This request holds the parameters needed by the the userrelateddataservice server.  After
     * setting any optional parameters, call the {@link ListInboxMessegeLog#execute()} method to
     * invoke the remote operation. <p> {@link ListInboxMessegeLog#initialize(com.google.api.client.go
     * ogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param type
     * @param userId
     * @since 1.13
     */
    protected ListInboxMessegeLog(java.lang.String type, java.lang.String userId) {
      super(Userrelateddataservice.this, "GET", REST_PATH, null, com.sep.androidbuddy.service.userrelateddataservice.model.MessegeLogCollection.class);
      this.type = com.google.api.client.util.Preconditions.checkNotNull(type, "Required parameter type must be specified.");
      this.userId = com.google.api.client.util.Preconditions.checkNotNull(userId, "Required parameter userId must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListInboxMessegeLog setAlt(java.lang.String alt) {
      return (ListInboxMessegeLog) super.setAlt(alt);
    }

    @Override
    public ListInboxMessegeLog setFields(java.lang.String fields) {
      return (ListInboxMessegeLog) super.setFields(fields);
    }

    @Override
    public ListInboxMessegeLog setKey(java.lang.String key) {
      return (ListInboxMessegeLog) super.setKey(key);
    }

    @Override
    public ListInboxMessegeLog setOauthToken(java.lang.String oauthToken) {
      return (ListInboxMessegeLog) super.setOauthToken(oauthToken);
    }

    @Override
    public ListInboxMessegeLog setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListInboxMessegeLog) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListInboxMessegeLog setQuotaUser(java.lang.String quotaUser) {
      return (ListInboxMessegeLog) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListInboxMessegeLog setUserIp(java.lang.String userIp) {
      return (ListInboxMessegeLog) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String type;

    /**

     */
    public java.lang.String getType() {
      return type;
    }

    public ListInboxMessegeLog setType(java.lang.String type) {
      this.type = type;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String userId;

    /**

     */
    public java.lang.String getUserId() {
      return userId;
    }

    public ListInboxMessegeLog setUserId(java.lang.String userId) {
      this.userId = userId;
      return this;
    }

    @Override
    public ListInboxMessegeLog set(String parameterName, Object value) {
      return (ListInboxMessegeLog) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listMessegeBytype".
   *
   * This request holds the parameters needed by the userrelateddataservice server.  After setting any
   * optional parameters, call the {@link ListMessegeBytype#execute()} method to invoke the remote
   * operation.
   *
   * @param type
   * @param userId
   * @return the request
   */
  public ListMessegeBytype listMessegeBytype(java.lang.String type, java.lang.String userId) throws java.io.IOException {
    ListMessegeBytype result = new ListMessegeBytype(type, userId);
    initialize(result);
    return result;
  }

  public class ListMessegeBytype extends UserrelateddataserviceRequest<com.sep.androidbuddy.service.userrelateddataservice.model.MessegeLogCollection> {

    private static final String REST_PATH = "messegelog/messegetype";

    /**
     * Create a request for the method "listMessegeBytype".
     *
     * This request holds the parameters needed by the the userrelateddataservice server.  After
     * setting any optional parameters, call the {@link ListMessegeBytype#execute()} method to invoke
     * the remote operation. <p> {@link ListMessegeBytype#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param type
     * @param userId
     * @since 1.13
     */
    protected ListMessegeBytype(java.lang.String type, java.lang.String userId) {
      super(Userrelateddataservice.this, "GET", REST_PATH, null, com.sep.androidbuddy.service.userrelateddataservice.model.MessegeLogCollection.class);
      this.type = com.google.api.client.util.Preconditions.checkNotNull(type, "Required parameter type must be specified.");
      this.userId = com.google.api.client.util.Preconditions.checkNotNull(userId, "Required parameter userId must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListMessegeBytype setAlt(java.lang.String alt) {
      return (ListMessegeBytype) super.setAlt(alt);
    }

    @Override
    public ListMessegeBytype setFields(java.lang.String fields) {
      return (ListMessegeBytype) super.setFields(fields);
    }

    @Override
    public ListMessegeBytype setKey(java.lang.String key) {
      return (ListMessegeBytype) super.setKey(key);
    }

    @Override
    public ListMessegeBytype setOauthToken(java.lang.String oauthToken) {
      return (ListMessegeBytype) super.setOauthToken(oauthToken);
    }

    @Override
    public ListMessegeBytype setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListMessegeBytype) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListMessegeBytype setQuotaUser(java.lang.String quotaUser) {
      return (ListMessegeBytype) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListMessegeBytype setUserIp(java.lang.String userIp) {
      return (ListMessegeBytype) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String type;

    /**

     */
    public java.lang.String getType() {
      return type;
    }

    public ListMessegeBytype setType(java.lang.String type) {
      this.type = type;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String userId;

    /**

     */
    public java.lang.String getUserId() {
      return userId;
    }

    public ListMessegeBytype setUserId(java.lang.String userId) {
      this.userId = userId;
      return this;
    }

    @Override
    public ListMessegeBytype set(String parameterName, Object value) {
      return (ListMessegeBytype) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listMessegeLogBySecificDate".
   *
   * This request holds the parameters needed by the userrelateddataservice server.  After setting any
   * optional parameters, call the {@link ListMessegeLogBySecificDate#execute()} method to invoke the
   * remote operation.
   *
   * @param messegeType
   * @param startTime
   * @param userId
   * @return the request
   */
  public ListMessegeLogBySecificDate listMessegeLogBySecificDate(java.lang.String messegeType, java.lang.String startTime, java.lang.String userId) throws java.io.IOException {
    ListMessegeLogBySecificDate result = new ListMessegeLogBySecificDate(messegeType, startTime, userId);
    initialize(result);
    return result;
  }

  public class ListMessegeLogBySecificDate extends UserrelateddataserviceRequest<com.sep.androidbuddy.service.userrelateddataservice.model.MessegeLogCollection> {

    private static final String REST_PATH = "messegelog/type";

    /**
     * Create a request for the method "listMessegeLogBySecificDate".
     *
     * This request holds the parameters needed by the the userrelateddataservice server.  After
     * setting any optional parameters, call the {@link ListMessegeLogBySecificDate#execute()} method
     * to invoke the remote operation. <p> {@link ListMessegeLogBySecificDate#initialize(com.google.ap
     * i.client.googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this
     * instance immediately after invoking the constructor. </p>
     *
     * @param messegeType
     * @param startTime
     * @param userId
     * @since 1.13
     */
    protected ListMessegeLogBySecificDate(java.lang.String messegeType, java.lang.String startTime, java.lang.String userId) {
      super(Userrelateddataservice.this, "GET", REST_PATH, null, com.sep.androidbuddy.service.userrelateddataservice.model.MessegeLogCollection.class);
      this.messegeType = com.google.api.client.util.Preconditions.checkNotNull(messegeType, "Required parameter messegeType must be specified.");
      this.startTime = com.google.api.client.util.Preconditions.checkNotNull(startTime, "Required parameter startTime must be specified.");
      this.userId = com.google.api.client.util.Preconditions.checkNotNull(userId, "Required parameter userId must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListMessegeLogBySecificDate setAlt(java.lang.String alt) {
      return (ListMessegeLogBySecificDate) super.setAlt(alt);
    }

    @Override
    public ListMessegeLogBySecificDate setFields(java.lang.String fields) {
      return (ListMessegeLogBySecificDate) super.setFields(fields);
    }

    @Override
    public ListMessegeLogBySecificDate setKey(java.lang.String key) {
      return (ListMessegeLogBySecificDate) super.setKey(key);
    }

    @Override
    public ListMessegeLogBySecificDate setOauthToken(java.lang.String oauthToken) {
      return (ListMessegeLogBySecificDate) super.setOauthToken(oauthToken);
    }

    @Override
    public ListMessegeLogBySecificDate setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListMessegeLogBySecificDate) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListMessegeLogBySecificDate setQuotaUser(java.lang.String quotaUser) {
      return (ListMessegeLogBySecificDate) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListMessegeLogBySecificDate setUserIp(java.lang.String userIp) {
      return (ListMessegeLogBySecificDate) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String messegeType;

    /**

     */
    public java.lang.String getMessegeType() {
      return messegeType;
    }

    public ListMessegeLogBySecificDate setMessegeType(java.lang.String messegeType) {
      this.messegeType = messegeType;
      return this;
    }

    @com.google.api.client.util.Key("start_time")
    private java.lang.String startTime;

    /**

     */
    public java.lang.String getStartTime() {
      return startTime;
    }

    public ListMessegeLogBySecificDate setStartTime(java.lang.String startTime) {
      this.startTime = startTime;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String userId;

    /**

     */
    public java.lang.String getUserId() {
      return userId;
    }

    public ListMessegeLogBySecificDate setUserId(java.lang.String userId) {
      this.userId = userId;
      return this;
    }

    @Override
    public ListMessegeLogBySecificDate set(String parameterName, Object value) {
      return (ListMessegeLogBySecificDate) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listMessegeLogByTimePeriod".
   *
   * This request holds the parameters needed by the userrelateddataservice server.  After setting any
   * optional parameters, call the {@link ListMessegeLogByTimePeriod#execute()} method to invoke the
   * remote operation.
   *
   * @param userId
   * @param startTime
   * @param endTime
   * @param messegeType
   * @return the request
   */
  public ListMessegeLogByTimePeriod listMessegeLogByTimePeriod(java.lang.String userId, java.lang.String startTime, java.lang.String endTime, java.lang.String messegeType) throws java.io.IOException {
    ListMessegeLogByTimePeriod result = new ListMessegeLogByTimePeriod(userId, startTime, endTime, messegeType);
    initialize(result);
    return result;
  }

  public class ListMessegeLogByTimePeriod extends UserrelateddataserviceRequest<com.sep.androidbuddy.service.userrelateddataservice.model.MessegeLogCollection> {

    private static final String REST_PATH = "messegelog/{userId}/{start_time}/{end_time}/{messegeType}";

    /**
     * Create a request for the method "listMessegeLogByTimePeriod".
     *
     * This request holds the parameters needed by the the userrelateddataservice server.  After
     * setting any optional parameters, call the {@link ListMessegeLogByTimePeriod#execute()} method
     * to invoke the remote operation. <p> {@link ListMessegeLogByTimePeriod#initialize(com.google.api
     * .client.googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this
     * instance immediately after invoking the constructor. </p>
     *
     * @param userId
     * @param startTime
     * @param endTime
     * @param messegeType
     * @since 1.13
     */
    protected ListMessegeLogByTimePeriod(java.lang.String userId, java.lang.String startTime, java.lang.String endTime, java.lang.String messegeType) {
      super(Userrelateddataservice.this, "GET", REST_PATH, null, com.sep.androidbuddy.service.userrelateddataservice.model.MessegeLogCollection.class);
      this.userId = com.google.api.client.util.Preconditions.checkNotNull(userId, "Required parameter userId must be specified.");
      this.startTime = com.google.api.client.util.Preconditions.checkNotNull(startTime, "Required parameter startTime must be specified.");
      this.endTime = com.google.api.client.util.Preconditions.checkNotNull(endTime, "Required parameter endTime must be specified.");
      this.messegeType = com.google.api.client.util.Preconditions.checkNotNull(messegeType, "Required parameter messegeType must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListMessegeLogByTimePeriod setAlt(java.lang.String alt) {
      return (ListMessegeLogByTimePeriod) super.setAlt(alt);
    }

    @Override
    public ListMessegeLogByTimePeriod setFields(java.lang.String fields) {
      return (ListMessegeLogByTimePeriod) super.setFields(fields);
    }

    @Override
    public ListMessegeLogByTimePeriod setKey(java.lang.String key) {
      return (ListMessegeLogByTimePeriod) super.setKey(key);
    }

    @Override
    public ListMessegeLogByTimePeriod setOauthToken(java.lang.String oauthToken) {
      return (ListMessegeLogByTimePeriod) super.setOauthToken(oauthToken);
    }

    @Override
    public ListMessegeLogByTimePeriod setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListMessegeLogByTimePeriod) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListMessegeLogByTimePeriod setQuotaUser(java.lang.String quotaUser) {
      return (ListMessegeLogByTimePeriod) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListMessegeLogByTimePeriod setUserIp(java.lang.String userIp) {
      return (ListMessegeLogByTimePeriod) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String userId;

    /**

     */
    public java.lang.String getUserId() {
      return userId;
    }

    public ListMessegeLogByTimePeriod setUserId(java.lang.String userId) {
      this.userId = userId;
      return this;
    }

    @com.google.api.client.util.Key("start_time")
    private java.lang.String startTime;

    /**

     */
    public java.lang.String getStartTime() {
      return startTime;
    }

    public ListMessegeLogByTimePeriod setStartTime(java.lang.String startTime) {
      this.startTime = startTime;
      return this;
    }

    @com.google.api.client.util.Key("end_time")
    private java.lang.String endTime;

    /**

     */
    public java.lang.String getEndTime() {
      return endTime;
    }

    public ListMessegeLogByTimePeriod setEndTime(java.lang.String endTime) {
      this.endTime = endTime;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String messegeType;

    /**

     */
    public java.lang.String getMessegeType() {
      return messegeType;
    }

    public ListMessegeLogByTimePeriod setMessegeType(java.lang.String messegeType) {
      this.messegeType = messegeType;
      return this;
    }

    @Override
    public ListMessegeLogByTimePeriod set(String parameterName, Object value) {
      return (ListMessegeLogByTimePeriod) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listMessegeLogByUser".
   *
   * This request holds the parameters needed by the userrelateddataservice server.  After setting any
   * optional parameters, call the {@link ListMessegeLogByUser#execute()} method to invoke the remote
   * operation.
   *
   * @param userId
   * @return the request
   */
  public ListMessegeLogByUser listMessegeLogByUser(java.lang.String userId) throws java.io.IOException {
    ListMessegeLogByUser result = new ListMessegeLogByUser(userId);
    initialize(result);
    return result;
  }

  public class ListMessegeLogByUser extends UserrelateddataserviceRequest<com.sep.androidbuddy.service.userrelateddataservice.model.MessegeLogCollection> {

    private static final String REST_PATH = "messegelog/byuser";

    /**
     * Create a request for the method "listMessegeLogByUser".
     *
     * This request holds the parameters needed by the the userrelateddataservice server.  After
     * setting any optional parameters, call the {@link ListMessegeLogByUser#execute()} method to
     * invoke the remote operation. <p> {@link ListMessegeLogByUser#initialize(com.google.api.client.g
     * oogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param userId
     * @since 1.13
     */
    protected ListMessegeLogByUser(java.lang.String userId) {
      super(Userrelateddataservice.this, "GET", REST_PATH, null, com.sep.androidbuddy.service.userrelateddataservice.model.MessegeLogCollection.class);
      this.userId = com.google.api.client.util.Preconditions.checkNotNull(userId, "Required parameter userId must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListMessegeLogByUser setAlt(java.lang.String alt) {
      return (ListMessegeLogByUser) super.setAlt(alt);
    }

    @Override
    public ListMessegeLogByUser setFields(java.lang.String fields) {
      return (ListMessegeLogByUser) super.setFields(fields);
    }

    @Override
    public ListMessegeLogByUser setKey(java.lang.String key) {
      return (ListMessegeLogByUser) super.setKey(key);
    }

    @Override
    public ListMessegeLogByUser setOauthToken(java.lang.String oauthToken) {
      return (ListMessegeLogByUser) super.setOauthToken(oauthToken);
    }

    @Override
    public ListMessegeLogByUser setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListMessegeLogByUser) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListMessegeLogByUser setQuotaUser(java.lang.String quotaUser) {
      return (ListMessegeLogByUser) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListMessegeLogByUser setUserIp(java.lang.String userIp) {
      return (ListMessegeLogByUser) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String userId;

    /**

     */
    public java.lang.String getUserId() {
      return userId;
    }

    public ListMessegeLogByUser setUserId(java.lang.String userId) {
      this.userId = userId;
      return this;
    }

    @Override
    public ListMessegeLogByUser set(String parameterName, Object value) {
      return (ListMessegeLogByUser) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listMissedCallLog".
   *
   * This request holds the parameters needed by the userrelateddataservice server.  After setting any
   * optional parameters, call the {@link ListMissedCallLog#execute()} method to invoke the remote
   * operation.
   *
   * @param type
   * @param userId
   * @return the request
   */
  public ListMissedCallLog listMissedCallLog(java.lang.String type, java.lang.String userId) throws java.io.IOException {
    ListMissedCallLog result = new ListMissedCallLog(type, userId);
    initialize(result);
    return result;
  }

  public class ListMissedCallLog extends UserrelateddataserviceRequest<com.sep.androidbuddy.service.userrelateddataservice.model.CallLogCollection> {

    private static final String REST_PATH = "calllog/calltype";

    /**
     * Create a request for the method "listMissedCallLog".
     *
     * This request holds the parameters needed by the the userrelateddataservice server.  After
     * setting any optional parameters, call the {@link ListMissedCallLog#execute()} method to invoke
     * the remote operation. <p> {@link ListMissedCallLog#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param type
     * @param userId
     * @since 1.13
     */
    protected ListMissedCallLog(java.lang.String type, java.lang.String userId) {
      super(Userrelateddataservice.this, "GET", REST_PATH, null, com.sep.androidbuddy.service.userrelateddataservice.model.CallLogCollection.class);
      this.type = com.google.api.client.util.Preconditions.checkNotNull(type, "Required parameter type must be specified.");
      this.userId = com.google.api.client.util.Preconditions.checkNotNull(userId, "Required parameter userId must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListMissedCallLog setAlt(java.lang.String alt) {
      return (ListMissedCallLog) super.setAlt(alt);
    }

    @Override
    public ListMissedCallLog setFields(java.lang.String fields) {
      return (ListMissedCallLog) super.setFields(fields);
    }

    @Override
    public ListMissedCallLog setKey(java.lang.String key) {
      return (ListMissedCallLog) super.setKey(key);
    }

    @Override
    public ListMissedCallLog setOauthToken(java.lang.String oauthToken) {
      return (ListMissedCallLog) super.setOauthToken(oauthToken);
    }

    @Override
    public ListMissedCallLog setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListMissedCallLog) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListMissedCallLog setQuotaUser(java.lang.String quotaUser) {
      return (ListMissedCallLog) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListMissedCallLog setUserIp(java.lang.String userIp) {
      return (ListMissedCallLog) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String type;

    /**

     */
    public java.lang.String getType() {
      return type;
    }

    public ListMissedCallLog setType(java.lang.String type) {
      this.type = type;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String userId;

    /**

     */
    public java.lang.String getUserId() {
      return userId;
    }

    public ListMissedCallLog setUserId(java.lang.String userId) {
      this.userId = userId;
      return this;
    }

    @Override
    public ListMissedCallLog set(String parameterName, Object value) {
      return (ListMissedCallLog) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "login".
   *
   * This request holds the parameters needed by the userrelateddataservice server.  After setting any
   * optional parameters, call the {@link Login#execute()} method to invoke the remote operation.
   *
   * @param id
   * @param password
   * @return the request
   */
  public Login login(java.lang.String id, java.lang.String password) throws java.io.IOException {
    Login result = new Login(id, password);
    initialize(result);
    return result;
  }

  public class Login extends UserrelateddataserviceRequest<com.sep.androidbuddy.service.userrelateddataservice.model.BooleanCollection> {

    private static final String REST_PATH = "booleancollection/{id}/{password}";

    /**
     * Create a request for the method "login".
     *
     * This request holds the parameters needed by the the userrelateddataservice server.  After
     * setting any optional parameters, call the {@link Login#execute()} method to invoke the remote
     * operation. <p> {@link
     * Login#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @param password
     * @since 1.13
     */
    protected Login(java.lang.String id, java.lang.String password) {
      super(Userrelateddataservice.this, "GET", REST_PATH, null, com.sep.androidbuddy.service.userrelateddataservice.model.BooleanCollection.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      this.password = com.google.api.client.util.Preconditions.checkNotNull(password, "Required parameter password must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public Login setAlt(java.lang.String alt) {
      return (Login) super.setAlt(alt);
    }

    @Override
    public Login setFields(java.lang.String fields) {
      return (Login) super.setFields(fields);
    }

    @Override
    public Login setKey(java.lang.String key) {
      return (Login) super.setKey(key);
    }

    @Override
    public Login setOauthToken(java.lang.String oauthToken) {
      return (Login) super.setOauthToken(oauthToken);
    }

    @Override
    public Login setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Login) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Login setQuotaUser(java.lang.String quotaUser) {
      return (Login) super.setQuotaUser(quotaUser);
    }

    @Override
    public Login setUserIp(java.lang.String userIp) {
      return (Login) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public Login setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String password;

    /**

     */
    public java.lang.String getPassword() {
      return password;
    }

    public Login setPassword(java.lang.String password) {
      this.password = password;
      return this;
    }

    @Override
    public Login set(String parameterName, Object value) {
      return (Login) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "setReminderForCallLog".
   *
   * This request holds the parameters needed by the userrelateddataservice server.  After setting any
   * optional parameters, call the {@link SetReminderForCallLog#execute()} method to invoke the remote
   * operation.
   *
   * @param description
   * @param time
   * @return the request
   */
  public SetReminderForCallLog setReminderForCallLog(java.lang.String description, com.google.api.client.util.DateTime time) throws java.io.IOException {
    SetReminderForCallLog result = new SetReminderForCallLog(description, time);
    initialize(result);
    return result;
  }

  public class SetReminderForCallLog extends UserrelateddataserviceRequest<Void> {

    private static final String REST_PATH = "addReminderForCallLog/{description}/{time}";

    /**
     * Create a request for the method "setReminderForCallLog".
     *
     * This request holds the parameters needed by the the userrelateddataservice server.  After
     * setting any optional parameters, call the {@link SetReminderForCallLog#execute()} method to
     * invoke the remote operation. <p> {@link SetReminderForCallLog#initialize(com.google.api.client.
     * googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param description
     * @param time
     * @since 1.13
     */
    protected SetReminderForCallLog(java.lang.String description, com.google.api.client.util.DateTime time) {
      super(Userrelateddataservice.this, "POST", REST_PATH, null, Void.class);
      this.description = com.google.api.client.util.Preconditions.checkNotNull(description, "Required parameter description must be specified.");
      this.time = com.google.api.client.util.Preconditions.checkNotNull(time, "Required parameter time must be specified.");
    }

    @Override
    public SetReminderForCallLog setAlt(java.lang.String alt) {
      return (SetReminderForCallLog) super.setAlt(alt);
    }

    @Override
    public SetReminderForCallLog setFields(java.lang.String fields) {
      return (SetReminderForCallLog) super.setFields(fields);
    }

    @Override
    public SetReminderForCallLog setKey(java.lang.String key) {
      return (SetReminderForCallLog) super.setKey(key);
    }

    @Override
    public SetReminderForCallLog setOauthToken(java.lang.String oauthToken) {
      return (SetReminderForCallLog) super.setOauthToken(oauthToken);
    }

    @Override
    public SetReminderForCallLog setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (SetReminderForCallLog) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public SetReminderForCallLog setQuotaUser(java.lang.String quotaUser) {
      return (SetReminderForCallLog) super.setQuotaUser(quotaUser);
    }

    @Override
    public SetReminderForCallLog setUserIp(java.lang.String userIp) {
      return (SetReminderForCallLog) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String description;

    /**

     */
    public java.lang.String getDescription() {
      return description;
    }

    public SetReminderForCallLog setDescription(java.lang.String description) {
      this.description = description;
      return this;
    }

    @com.google.api.client.util.Key
    private com.google.api.client.util.DateTime time;

    /**

     */
    public com.google.api.client.util.DateTime getTime() {
      return time;
    }

    public SetReminderForCallLog setTime(com.google.api.client.util.DateTime time) {
      this.time = time;
      return this;
    }

    @Override
    public SetReminderForCallLog set(String parameterName, Object value) {
      return (SetReminderForCallLog) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Userrelateddataservice}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Userrelateddataservice}. */
    @Override
    public Userrelateddataservice build() {
      return new Userrelateddataservice(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link UserrelateddataserviceRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setUserrelateddataserviceRequestInitializer(
        UserrelateddataserviceRequestInitializer userrelateddataserviceRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(userrelateddataserviceRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
