/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-09-18 at 15:48:00 UTC 
 * Modify at your own risk.
 */

package com.sep.androidbuddy.entity.userrelateddataendpoint.model;

/**
 * Model definition for User.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the userrelateddataendpoint. For a detailed explanation
 * see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class User extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<BatteryLowMesseges> battryMessegelist;

  static {
    // hack to force ProGuard to consider BatteryLowMesseges used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(BatteryLowMesseges.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<CallLog> calllog;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Contact contact;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Contact> contactList;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String deviceId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<BrowserHistoryItem> historylist;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<LastLogDetail> lastlogdetail;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<MessegeLog> messegelist;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String password;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userId;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<BatteryLowMesseges> getBattryMessegelist() {
    return battryMessegelist;
  }

  /**
   * @param battryMessegelist battryMessegelist or {@code null} for none
   */
  public User setBattryMessegelist(java.util.List<BatteryLowMesseges> battryMessegelist) {
    this.battryMessegelist = battryMessegelist;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<CallLog> getCalllog() {
    return calllog;
  }

  /**
   * @param calllog calllog or {@code null} for none
   */
  public User setCalllog(java.util.List<CallLog> calllog) {
    this.calllog = calllog;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Contact getContact() {
    return contact;
  }

  /**
   * @param contact contact or {@code null} for none
   */
  public User setContact(Contact contact) {
    this.contact = contact;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Contact> getContactList() {
    return contactList;
  }

  /**
   * @param contactList contactList or {@code null} for none
   */
  public User setContactList(java.util.List<Contact> contactList) {
    this.contactList = contactList;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDeviceId() {
    return deviceId;
  }

  /**
   * @param deviceId deviceId or {@code null} for none
   */
  public User setDeviceId(java.lang.String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<BrowserHistoryItem> getHistorylist() {
    return historylist;
  }

  /**
   * @param historylist historylist or {@code null} for none
   */
  public User setHistorylist(java.util.List<BrowserHistoryItem> historylist) {
    this.historylist = historylist;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<LastLogDetail> getLastlogdetail() {
    return lastlogdetail;
  }

  /**
   * @param lastlogdetail lastlogdetail or {@code null} for none
   */
  public User setLastlogdetail(java.util.List<LastLogDetail> lastlogdetail) {
    this.lastlogdetail = lastlogdetail;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<MessegeLog> getMessegelist() {
    return messegelist;
  }

  /**
   * @param messegelist messegelist or {@code null} for none
   */
  public User setMessegelist(java.util.List<MessegeLog> messegelist) {
    this.messegelist = messegelist;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public User setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPassword() {
    return password;
  }

  /**
   * @param password password or {@code null} for none
   */
  public User setPassword(java.lang.String password) {
    this.password = password;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserId() {
    return userId;
  }

  /**
   * @param userId userId or {@code null} for none
   */
  public User setUserId(java.lang.String userId) {
    this.userId = userId;
    return this;
  }

  @Override
  public User set(String fieldName, Object value) {
    return (User) super.set(fieldName, value);
  }

  @Override
  public User clone() {
    return (User) super.clone();
  }

}
